### ISSUE TITLE
Feature Request: Admin should be able to edit badge image

### ISSUE THREAD

**Issue by rohit1290** [iionly/elggx_badges#1]
Now suppose I have a badge which has been assigned to 100 users. I want to change the badge image. Its not possible for the admin to create new badge for the new image and again assign the new badge to those 100 user.

So I think there should be an option to edit the badge image as well.

**Comment by iionly** [comment]
It's very, very likely that such a feature will be included in the next release (shouldn't be too long until ready).

**Comment by iionly** [comment]
Feature added in version 1.10.14.

**Comment by rohit1290** [comment]
There is an issue with the current code. According to the current source code, If I don't select an image file for the badge and save it. It will remove the old file and show an image error. If the admin want to edit the name or description of the badge, he/she have to select an image every time for the changes made to the badge.

This is how the image looks like before editing:
![before save](https://cloud.githubusercontent.com/assets/2772844/10412090/a3111b5a-6f98-11e5-9416-3fa09cc56ce0.PNG)

This is how it looks like after editing (When no image was selected)
![after save](https://cloud.githubusercontent.com/assets/2772844/10412089/a2e0bd3e-6f98-11e5-89bf-00874be0d241.PNG)

**Comment by iionly** [comment]
Sorry. I don't know how I could miss that... most likely due to some last minute "optimizations"...

It should work in version 1.10.15 (2.0.1 respectively).
