### ISSUE TITLE
<td> tags used in the icon view are breaking tables

### ISSUE THREAD

**Issue by juho-jaakkola** [iionly/elggx_badges#2]
When user icon is used within a table, the `<td>` tags are breaking the table layout: 
 - https://github.com/iionly/elggx_badges/blob/master/views/default/icon/user/default.php#L72
 - https://github.com/iionly/elggx_badges/blob/master/views/default/icon/user/default.php#L136

**Comment by iionly** [comment]
I've no idea at the moment why the `<td>` tags are even there. It seems to work fine without. Maybe the tags were needed in the original version of the plugin (for Elgg 1.7 and earlier) and I just kept them back then when updating the plugin for 1.8. Or I had added them on my own back then to get something working (as I don't see them in the old original code) but then forgot to remove them when getting it to work the way it's done presently...
